language: 
  - cpp

os:
  - linux

compiler:
  - gcc

env:
    - MPI=mpich3
    - MPI=mpich2
    - MPI=mpich1
    - MPI=openmpi
    
matrix:
  allow_failures:
    - env: MPI=mpich3
    
branches:
  only:
    - master
    - dev
cache:
  apt: true
  
before_install:
    - sudo apt-get update -q
    - sh install-mpi.sh $MPI

sudo: required

script:
  - bash ci_build.sh
